version: '3.8'
services:
  php:
    volumes:
      - ${SMF_VOLUME}
    working_dir: ${WORKING_DIR}
    build:
      context: .
      args:
        PHP_VERSION: ${PHP_VERSION}
        DB_DRIVER: ${DB_DRIVER}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_NAME: ${DB_NAME}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        MYSQL_VERSION: ${MYSQL_VERSION}
        PHP_REPOSITORY: ${PHP_REPOSITORY}
        TIMEZONE: ${TIMEZONE}
      dockerfile: docker/php/Dockerfile
    container_name: ${CONTAINER_PREFIX}php

  nginx:
    ports:
      - "${EXTERNAL_PORT}:${NGINX_PORT}"
    volumes:
      - ${SMF_VOLUME}
      - ./site.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
    image: nginx:${NGINX_VERSION}
    depends_on:
      - php
    container_name: ${CONTAINER_PREFIX}nginx

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${EXT_DB_PORT}:${DB_PORT}"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ${SMF_VOLUME}
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    container_name: ${CONTAINER_PREFIX}mysql
